version: '3.8'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: bash -c "npm i && npm run start"


  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: "server/.env"
    command: bash -c "pip install -r requirements.txt && fastapi run app.py"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    env_file: "server/.env"
    ports: 
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: