# Generated by Django 5.0.3 on 2024-05-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_status',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
