# Generated by Django 5.0.3 on 2024-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sended_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
